# docker-compose up -d
# the above command will start a container as the apache server to run phppgadmin
# environment variables is defined in .env file or the local env
# docker-compose down, to stop and remove service related resources
version: "3"
services:
  pgadmin:
    # replace username/repo:tag with your name and image details
    image: keepitcool/phppgadmin
    environment:
      DB_HOST: postgres
    ports:
      - "80:80"
networks:
  default:
    external:
      # make sure the external network is created in advance using below command
      # docker network create --driver bridge development
      name: development
